//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChinaFood.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChinaFood.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Added On.
        /// </summary>
        public static string AddedOn {
            get {
                return ResourceManager.GetString("AddedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add To Cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Armenian.
        /// </summary>
        public static string Armenian {
            get {
                return ResourceManager.GetString("Armenian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на China.
        /// </summary>
        public static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на China Town– Armenian online service for ordering eastern food. You will enjoy our website if you value your time, money and ability of choice. You can easily find the dish you want in a few seconds. Among assortment offered: chinesse food, japannesse food, various drinks. Discover the authentic flavors of Chinese cuisine with our convenient delivery service! We offer a wide selection of dishes prepared using traditional recipes and fresh ingredients. Our menu includes everything from spicy noodles and rice  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string ChinaTownDesc {
            get {
                return ResourceManager.GetString("ChinaTownDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Online platform for ordering eastern food.
        /// </summary>
        public static string ChinaTownTitle {
            get {
                return ResourceManager.GetString("ChinaTownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chinese Dishes.
        /// </summary>
        public static string ChineseDishes {
            get {
                return ResourceManager.GetString("ChineseDishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chinesse.
        /// </summary>
        public static string Chinesse {
            get {
                return ResourceManager.GetString("Chinesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на China Town.
        /// </summary>
        public static string CompName {
            get {
                return ResourceManager.GetString("CompName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our website provides responsive customer support to handle any questions or concerns. We guarantee the quality of our food, and any complaints will be addressed quickly, ensuring customer trust and satisfaction..
        /// </summary>
        public static string CustomerSupportAndQualityAssuranceDesc {
            get {
                return ResourceManager.GetString("CustomerSupportAndQualityAssuranceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer Support and Quality Assurance.
        /// </summary>
        public static string CustomerSupportAndQualityAssuranceTitle {
            get {
                return ResourceManager.GetString("CustomerSupportAndQualityAssuranceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dish or drink name.
        /// </summary>
        public static string DishName {
            get {
                return ResourceManager.GetString("DishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dish type.
        /// </summary>
        public static string DishType {
            get {
                return ResourceManager.GetString("DishType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drink.
        /// </summary>
        public static string Drink {
            get {
                return ResourceManager.GetString("Drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drinks.
        /// </summary>
        public static string Drinks {
            get {
                return ResourceManager.GetString("Drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The website’s user interface is designed for simplicity, allowing customers to easily find their desired dishes, add them to the cart, and place their orders in just a few clicks..
        /// </summary>
        public static string EasyOrderingProcessDesc {
            get {
                return ResourceManager.GetString("EasyOrderingProcessDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Easy ordering process.
        /// </summary>
        public static string EasyOrderingProcessTitle {
            get {
                return ResourceManager.GetString("EasyOrderingProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customers can order their favorite Chinese dishes online and have them delivered to their doorstep, saving time and making the process as convenient as possible..
        /// </summary>
        public static string FastAndConvenientDeliveryDesc {
            get {
                return ResourceManager.GetString("FastAndConvenientDeliveryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fast and convenient delivery.
        /// </summary>
        public static string FastAndConvenientDeliveryTitle {
            get {
                return ResourceManager.GetString("FastAndConvenientDeliveryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Favorite Dishes.
        /// </summary>
        public static string FavoriteDishes {
            get {
                return ResourceManager.GetString("FavoriteDishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All dishes are made with fresh ingredients using traditional Chinese recipes, ensuring genuine flavors and high-quality meals..
        /// </summary>
        public static string FreshIngredientsAndAuthenticRecipesDesc {
            get {
                return ResourceManager.GetString("FreshIngredientsAndAuthenticRecipesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fresh ingredients and authentic recipes.
        /// </summary>
        public static string FreshIngredientsAndAuthenticRecipesTitle {
            get {
                return ResourceManager.GetString("FreshIngredientsAndAuthenticRecipesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hot Dishes.
        /// </summary>
        public static string HotDishes {
            get {
                return ResourceManager.GetString("HotDishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input dish or drink name .
        /// </summary>
        public static string InputDishName {
            get {
                return ResourceManager.GetString("InputDishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Japan.
        /// </summary>
        public static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Japanese Dishes.
        /// </summary>
        public static string JapaneseDishes {
            get {
                return ResourceManager.GetString("JapaneseDishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Japanesse.
        /// </summary>
        public static string Japanesse {
            get {
                return ResourceManager.GetString("Japanesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximal price.
        /// </summary>
        public static string MaxPrice {
            get {
                return ResourceManager.GetString("MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimal price.
        /// </summary>
        public static string MinPrice {
            get {
                return ResourceManager.GetString("MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Price.
        /// </summary>
        public static string NewPrice {
            get {
                return ResourceManager.GetString("NewPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old Price.
        /// </summary>
        public static string OldPrice {
            get {
                return ResourceManager.GetString("OldPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Taste of China:.
        /// </summary>
        public static string PosterTitle1 {
            get {
                return ResourceManager.GetString("PosterTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fast delivery of authentic Chinese dishes.
        /// </summary>
        public static string PosterTitle2 {
            get {
                return ResourceManager.GetString("PosterTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Proceed To Checkout.
        /// </summary>
        public static string ProceedToCheckout {
            get {
                return ResourceManager.GetString("ProceedToCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Dish Type.
        /// </summary>
        public static string SelectDishType {
            get {
                return ResourceManager.GetString("SelectDishType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Sub Category.
        /// </summary>
        public static string SelectSubCategory {
            get {
                return ResourceManager.GetString("SelectSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Less.
        /// </summary>
        public static string ShowLess {
            get {
                return ResourceManager.GetString("ShowLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show More.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regular promotions, discounts for large orders, or loyalty programs for returning customers increase the appeal of the service..
        /// </summary>
        public static string SpecialOffersAndDiscountsDesc {
            get {
                return ResourceManager.GetString("SpecialOffersAndDiscountsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Special offers and discounts.
        /// </summary>
        public static string SpecialOffersAndDiscountsTitle {
            get {
                return ResourceManager.GetString("SpecialOffersAndDiscountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SubCategory.
        /// </summary>
        public static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit Order.
        /// </summary>
        public static string SubmitOrder {
            get {
                return ResourceManager.GetString("SubmitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Swipe To Browse.
        /// </summary>
        public static string SwipeToBrowse {
            get {
                return ResourceManager.GetString("SwipeToBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View Dish Info.
        /// </summary>
        public static string ViewDishInfo {
            get {
                return ResourceManager.GetString("ViewDishInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The menu offers a variety of popular Chinese dishes, from dim sum to Peking duck, satisfying the tastes of a diverse range of customers..
        /// </summary>
        public static string WideSelectionOfTraditionalDishesDesc {
            get {
                return ResourceManager.GetString("WideSelectionOfTraditionalDishesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wide selection of traditional dishes.
        /// </summary>
        public static string WideSelectionOfTraditionalDishesTitle {
            get {
                return ResourceManager.GetString("WideSelectionOfTraditionalDishesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your Cart.
        /// </summary>
        public static string YourCart {
            get {
                return ResourceManager.GetString("YourCart", resourceCulture);
            }
        }
    }
}
